/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserRequest
 */
export interface CreateUserRequest {
    /**
     * Email
     * @type {string}
     * @memberof CreateUserRequest
     */
    email: string;
    /**
     * Password1
     * @type {string}
     * @memberof CreateUserRequest
     */
    password1: string;
    /**
     * Password2
     * @type {string}
     * @memberof CreateUserRequest
     */
    password2: string;
    /**
     * username
     * @type {string}
     * @memberof CreateUserRequest
     */
    username: string;
}

/**
 * Check if a given object implements the CreateUserRequest interface.
 */
export function instanceOfCreateUserRequest(value: object): boolean {
    if (!('email' in value)) return false;
    if (!('password1' in value)) return false;
    if (!('password2' in value)) return false;
    if (!('username' in value)) return false;
    return true;
}

export function CreateUserRequestFromJSON(json: any): CreateUserRequest {
    return CreateUserRequestFromJSONTyped(json, false);
}

export function CreateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password1': json['password1'],
        'password2': json['password2'],
        'username': json['username'],
    };
}

export function CreateUserRequestToJSON(value?: CreateUserRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password1': value['password1'],
        'password2': value['password2'],
        'username': value['username'],
    };
}

