/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkspaceResponse
 */
export interface CreateWorkspaceResponse {
    /**
     * ID
     * @type {number}
     * @memberof CreateWorkspaceResponse
     */
    id: number;
}

/**
 * Check if a given object implements the CreateWorkspaceResponse interface.
 */
export function instanceOfCreateWorkspaceResponse(value: object): boolean {
    if (!('id' in value)) return false;
    return true;
}

export function CreateWorkspaceResponseFromJSON(json: any): CreateWorkspaceResponse {
    return CreateWorkspaceResponseFromJSONTyped(json, false);
}

export function CreateWorkspaceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkspaceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CreateWorkspaceResponseToJSON(value?: CreateWorkspaceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

