/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEmailVerificationRequest
 */
export interface CreateEmailVerificationRequest {
    /**
     * Email
     * @type {string}
     * @memberof CreateEmailVerificationRequest
     */
    email: string;
}

/**
 * Check if a given object implements the CreateEmailVerificationRequest interface.
 */
export function instanceOfCreateEmailVerificationRequest(value: object): boolean {
    if (!('email' in value)) return false;
    return true;
}

export function CreateEmailVerificationRequestFromJSON(json: any): CreateEmailVerificationRequest {
    return CreateEmailVerificationRequestFromJSONTyped(json, false);
}

export function CreateEmailVerificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmailVerificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function CreateEmailVerificationRequestToJSON(value?: CreateEmailVerificationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

