/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkspaceRequest
 */
export interface CreateWorkspaceRequest {
    /**
     * Title
     * @type {string}
     * @memberof CreateWorkspaceRequest
     */
    title: string;
}

/**
 * Check if a given object implements the CreateWorkspaceRequest interface.
 */
export function instanceOfCreateWorkspaceRequest(value: object): boolean {
    if (!('title' in value)) return false;
    return true;
}

export function CreateWorkspaceRequestFromJSON(json: any): CreateWorkspaceRequest {
    return CreateWorkspaceRequestFromJSONTyped(json, false);
}

export function CreateWorkspaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkspaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
    };
}

export function CreateWorkspaceRequestToJSON(value?: CreateWorkspaceRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
    };
}

