/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectResponse
 */
export interface CreateProjectResponse {
    /**
     * ID
     * @type {number}
     * @memberof CreateProjectResponse
     */
    id: number;
}

/**
 * Check if a given object implements the CreateProjectResponse interface.
 */
export function instanceOfCreateProjectResponse(value: object): boolean {
    if (!('id' in value)) return false;
    return true;
}

export function CreateProjectResponseFromJSON(json: any): CreateProjectResponse {
    return CreateProjectResponseFromJSONTyped(json, false);
}

export function CreateProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CreateProjectResponseToJSON(value?: CreateProjectResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

