/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailVerificationRequest
 */
export interface EmailVerificationRequest {
    /**
     * Email
     * @type {string}
     * @memberof EmailVerificationRequest
     */
    email: string;
}

/**
 * Check if a given object implements the EmailVerificationRequest interface.
 */
export function instanceOfEmailVerificationRequest(value: object): boolean {
    if (!('email' in value)) return false;
    return true;
}

export function EmailVerificationRequestFromJSON(json: any): EmailVerificationRequest {
    return EmailVerificationRequestFromJSONTyped(json, false);
}

export function EmailVerificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailVerificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function EmailVerificationRequestToJSON(value?: EmailVerificationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

