/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EmailVerificationType = {
    Signup: 'signup',
    ResetPassword: 'reset_password'
} as const;
export type EmailVerificationType = typeof EmailVerificationType[keyof typeof EmailVerificationType];


export function instanceOfEmailVerificationType(value: any): boolean {
    return Object.values(EmailVerificationType).includes(value);
}

export function EmailVerificationTypeFromJSON(json: any): EmailVerificationType {
    return EmailVerificationTypeFromJSONTyped(json, false);
}

export function EmailVerificationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailVerificationType {
    return json as EmailVerificationType;
}

export function EmailVerificationTypeToJSON(value?: EmailVerificationType | null): any {
    return value as any;
}

