/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExperimentTimeslotRead
 */
export interface ExperimentTimeslotRead {
    /**
     * ID
     * @type {number}
     * @memberof ExperimentTimeslotRead
     */
    id: number;
    /**
     * Experiment start time
     * @type {string}
     * @memberof ExperimentTimeslotRead
     */
    startTime: string;
    /**
     * Experiment end time
     * @type {string}
     * @memberof ExperimentTimeslotRead
     */
    endTime: string;
    /**
     * Maximum number of exparticipants per session
     * @type {number}
     * @memberof ExperimentTimeslotRead
     */
    maxParticipants: number;
}

/**
 * Check if a given object implements the ExperimentTimeslotRead interface.
 */
export function instanceOfExperimentTimeslotRead(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('startTime' in value)) return false;
    if (!('endTime' in value)) return false;
    if (!('maxParticipants' in value)) return false;
    return true;
}

export function ExperimentTimeslotReadFromJSON(json: any): ExperimentTimeslotRead {
    return ExperimentTimeslotReadFromJSONTyped(json, false);
}

export function ExperimentTimeslotReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentTimeslotRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startTime': json['start_time'],
        'endTime': json['end_time'],
        'maxParticipants': json['max_participants'],
    };
}

export function ExperimentTimeslotReadToJSON(value?: ExperimentTimeslotRead | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'start_time': value['startTime'],
        'end_time': value['endTime'],
        'max_participants': value['maxParticipants'],
    };
}

