/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExperimentTimeslotRequest
 */
export interface ExperimentTimeslotRequest {
    /**
     * 
     * @type {number}
     * @memberof ExperimentTimeslotRequest
     */
    id?: number;
    /**
     * Experiment start time
     * @type {string}
     * @memberof ExperimentTimeslotRequest
     */
    startTime: string;
    /**
     * Experiment end time
     * @type {string}
     * @memberof ExperimentTimeslotRequest
     */
    endTime: string;
    /**
     * Maximum number of experiment participants
     * @type {number}
     * @memberof ExperimentTimeslotRequest
     */
    maxParticipants: number;
}

/**
 * Check if a given object implements the ExperimentTimeslotRequest interface.
 */
export function instanceOfExperimentTimeslotRequest(value: object): boolean {
    if (!('startTime' in value)) return false;
    if (!('endTime' in value)) return false;
    if (!('maxParticipants' in value)) return false;
    return true;
}

export function ExperimentTimeslotRequestFromJSON(json: any): ExperimentTimeslotRequest {
    return ExperimentTimeslotRequestFromJSONTyped(json, false);
}

export function ExperimentTimeslotRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentTimeslotRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'startTime': json['start_time'],
        'endTime': json['end_time'],
        'maxParticipants': json['max_participants'],
    };
}

export function ExperimentTimeslotRequestToJSON(value?: ExperimentTimeslotRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'start_time': value['startTime'],
        'end_time': value['endTime'],
        'max_participants': value['maxParticipants'],
    };
}

