/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProjectListResponse
 */
export interface GetProjectListResponse {
    /**
     * ID
     * @type {number}
     * @memberof GetProjectListResponse
     */
    id: number;
    /**
     * Workspace ID
     * @type {number}
     * @memberof GetProjectListResponse
     */
    workspaceId: number;
    /**
     * Title
     * @type {string}
     * @memberof GetProjectListResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof GetProjectListResponse
     */
    description?: string;
    /**
     * Whether the project is public
     * @type {boolean}
     * @memberof GetProjectListResponse
     */
    isPublic: boolean;
    /**
     * Number of experiment participants
     * @type {number}
     * @memberof GetProjectListResponse
     */
    joinedParticipants: number;
    /**
     * Maximum number of experiment participants
     * @type {number}
     * @memberof GetProjectListResponse
     */
    maxParticipants: number;
    /**
     * 
     * @type {Date}
     * @memberof GetProjectListResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetProjectListResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the GetProjectListResponse interface.
 */
export function instanceOfGetProjectListResponse(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('workspaceId' in value)) return false;
    if (!('title' in value)) return false;
    if (!('isPublic' in value)) return false;
    if (!('joinedParticipants' in value)) return false;
    if (!('maxParticipants' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function GetProjectListResponseFromJSON(json: any): GetProjectListResponse {
    return GetProjectListResponseFromJSONTyped(json, false);
}

export function GetProjectListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProjectListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workspaceId': json['workspace_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'isPublic': json['is_public'],
        'joinedParticipants': json['joined_participants'],
        'maxParticipants': json['max_participants'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function GetProjectListResponseToJSON(value?: GetProjectListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'workspace_id': value['workspaceId'],
        'title': value['title'],
        'description': value['description'],
        'is_public': value['isPublic'],
        'joined_participants': value['joinedParticipants'],
        'max_participants': value['maxParticipants'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

