/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserListResponse
 */
export interface GetUserListResponse {
    /**
     * ID
     * @type {number}
     * @memberof GetUserListResponse
     */
    id: number;
    /**
     * Email
     * @type {string}
     * @memberof GetUserListResponse
     */
    email: string;
    /**
     * username
     * @type {string}
     * @memberof GetUserListResponse
     */
    username: string;
}

/**
 * Check if a given object implements the GetUserListResponse interface.
 */
export function instanceOfGetUserListResponse(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('email' in value)) return false;
    if (!('username' in value)) return false;
    return true;
}

export function GetUserListResponseFromJSON(json: any): GetUserListResponse {
    return GetUserListResponseFromJSONTyped(json, false);
}

export function GetUserListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'username': json['username'],
    };
}

export function GetUserListResponseToJSON(value?: GetUserListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'email': value['email'],
        'username': value['username'],
    };
}

