/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWorkspaceListResponse
 */
export interface GetWorkspaceListResponse {
    /**
     * ID
     * @type {number}
     * @memberof GetWorkspaceListResponse
     */
    id: number;
    /**
     * Title
     * @type {string}
     * @memberof GetWorkspaceListResponse
     */
    title: string;
    /**
     * Order
     * @type {number}
     * @memberof GetWorkspaceListResponse
     */
    orderNo: number;
}

/**
 * Check if a given object implements the GetWorkspaceListResponse interface.
 */
export function instanceOfGetWorkspaceListResponse(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('title' in value)) return false;
    if (!('orderNo' in value)) return false;
    return true;
}

export function GetWorkspaceListResponseFromJSON(json: any): GetWorkspaceListResponse {
    return GetWorkspaceListResponseFromJSONTyped(json, false);
}

export function GetWorkspaceListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkspaceListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'orderNo': json['order_no'],
    };
}

export function GetWorkspaceListResponseToJSON(value?: GetWorkspaceListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'order_no': value['orderNo'],
    };
}

