/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProjectTypeEnum = {
    Survey: 'survey',
    Experiment: 'experiment'
} as const;
export type ProjectTypeEnum = typeof ProjectTypeEnum[keyof typeof ProjectTypeEnum];


export function instanceOfProjectTypeEnum(value: any): boolean {
    return Object.values(ProjectTypeEnum).includes(value);
}

export function ProjectTypeEnumFromJSON(json: any): ProjectTypeEnum {
    return ProjectTypeEnumFromJSONTyped(json, false);
}

export function ProjectTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectTypeEnum {
    return json as ProjectTypeEnum;
}

export function ProjectTypeEnumToJSON(value?: ProjectTypeEnum | null): any {
    return value as any;
}

