/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshTokenRequest
 */
export interface RefreshTokenRequest {
    /**
     * Token
     * @type {string}
     * @memberof RefreshTokenRequest
     */
    token: string;
    /**
     * Refresh token
     * @type {string}
     * @memberof RefreshTokenRequest
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the RefreshTokenRequest interface.
 */
export function instanceOfRefreshTokenRequest(value: object): boolean {
    if (!('token' in value)) return false;
    if (!('refreshToken' in value)) return false;
    return true;
}

export function RefreshTokenRequestFromJSON(json: any): RefreshTokenRequest {
    return RefreshTokenRequestFromJSONTyped(json, false);
}

export function RefreshTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'refreshToken': json['refresh_token'],
    };
}

export function RefreshTokenRequestToJSON(value?: RefreshTokenRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
        'refresh_token': value['refreshToken'],
    };
}

