/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWorkspaceRequest
 */
export interface UpdateWorkspaceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkspaceRequest
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateWorkspaceRequest
     */
    orderNo?: number;
}

/**
 * Check if a given object implements the UpdateWorkspaceRequest interface.
 */
export function instanceOfUpdateWorkspaceRequest(value: object): boolean {
    return true;
}

export function UpdateWorkspaceRequestFromJSON(json: any): UpdateWorkspaceRequest {
    return UpdateWorkspaceRequestFromJSONTyped(json, false);
}

export function UpdateWorkspaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWorkspaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'orderNo': json['order_no'] == null ? undefined : json['order_no'],
    };
}

export function UpdateWorkspaceRequestToJSON(value?: UpdateWorkspaceRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'order_no': value['orderNo'],
    };
}

