/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateEmailRequest
 */
export interface ValidateEmailRequest {
    /**
     * Email
     * @type {string}
     * @memberof ValidateEmailRequest
     */
    email: string;
}

/**
 * Check if a given object implements the ValidateEmailRequest interface.
 */
export function instanceOfValidateEmailRequest(value: object): boolean {
    if (!('email' in value)) return false;
    return true;
}

export function ValidateEmailRequestFromJSON(json: any): ValidateEmailRequest {
    return ValidateEmailRequestFromJSONTyped(json, false);
}

export function ValidateEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ValidateEmailRequestToJSON(value?: ValidateEmailRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

