/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyEmailRequest
 */
export interface VerifyEmailRequest {
    /**
     * Email
     * @type {string}
     * @memberof VerifyEmailRequest
     */
    email: string;
    /**
     * Code
     * @type {string}
     * @memberof VerifyEmailRequest
     */
    code: string;
}

/**
 * Check if a given object implements the VerifyEmailRequest interface.
 */
export function instanceOfVerifyEmailRequest(value: object): boolean {
    if (!('email' in value)) return false;
    if (!('code' in value)) return false;
    return true;
}

export function VerifyEmailRequestFromJSON(json: any): VerifyEmailRequest {
    return VerifyEmailRequestFromJSONTyped(json, false);
}

export function VerifyEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'code': json['code'],
    };
}

export function VerifyEmailRequestToJSON(value?: VerifyEmailRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'code': value['code'],
    };
}

