/* tslint:disable */
/* eslint-disable */
/**
 * DingDong Survey
 * dingdong-survey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUserRequest
 */
export interface CreateUserRequest {
    /**
     * Email
     * @type {string}
     * @memberof CreateUserRequest
     */
    'email': string;
    /**
     * Password
     * @type {string}
     * @memberof CreateUserRequest
     */
    'password': string;
    /**
     * Username
     * @type {string}
     * @memberof CreateUserRequest
     */
    'username': string;
}

