/* tslint:disable */
/* eslint-disable */
/**
 * DingDong Survey
 * dingdong-survey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const EmailVerificationType = {
    signup: 'signup',
    resetPassword: 'resetPassword'
} as const;

export type EmailVerificationType = typeof EmailVerificationType[keyof typeof EmailVerificationType];



