/* tslint:disable */
/* eslint-disable */
/**
 * DingDong Survey
 * dingdong-survey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserOauthResponseDTO } from './user-oauth-response-dto';

/**
 * 
 * @export
 * @interface GetUserListResponseDTO
 */
export interface GetUserListResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof GetUserListResponseDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof GetUserListResponseDTO
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof GetUserListResponseDTO
     */
    'username': string;
    /**
     * 
     * @type {boolean}
     * @memberof GetUserListResponseDTO
     */
    'is_admin': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetUserListResponseDTO
     */
    'is_deleted': boolean;
    /**
     * 
     * @type {Array<UserOauthResponseDTO>}
     * @memberof GetUserListResponseDTO
     */
    'oauth_accounts': Array<UserOauthResponseDTO>;
}

