/* tslint:disable */
/* eslint-disable */
/**
 * DingDong Survey
 * dingdong-survey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExperimentTimeslotDTO } from './experiment-timeslot-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ExperimentTypeEnum } from './experiment-type-enum';

/**
 * 
 * @export
 * @interface GetProjectResponseDTO
 */
export interface GetProjectResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof GetProjectResponseDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof GetProjectResponseDTO
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof GetProjectResponseDTO
     */
    'description': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetProjectResponseDTO
     */
    'isPublic': boolean;
    /**
     * 
     * @type {string}
     * @memberof GetProjectResponseDTO
     */
    'startDate': string | null;
    /**
     * 
     * @type {string}
     * @memberof GetProjectResponseDTO
     */
    'endDate': string | null;
    /**
     * Experimental exclusion days
     * @type {Array<string>}
     * @memberof GetProjectResponseDTO
     */
    'excludedDates': Array<string>;
    /**
     * Time information of experiment
     * @type {Array<ExperimentTimeslotDTO>}
     * @memberof GetProjectResponseDTO
     */
    'experimentTimeslots': Array<ExperimentTimeslotDTO>;
    /**
     * Maximum number of experiment participants
     * @type {number}
     * @memberof GetProjectResponseDTO
     */
    'maxParticipants': number;
    /**
     * 
     * @type {ExperimentTypeEnum}
     * @memberof GetProjectResponseDTO
     */
    'experimentType': ExperimentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetProjectResponseDTO
     */
    'location': string | null;
    /**
     * 
     * @type {string}
     * @memberof GetProjectResponseDTO
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof GetProjectResponseDTO
     */
    'updatedAt': string | null;
}



