/* tslint:disable */
/* eslint-disable */
/**
 * DingDong Survey
 * dingdong-survey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetWorkspaceRepsonseDTO
 */
export interface GetWorkspaceRepsonseDTO {
    /**
     * ID
     * @type {number}
     * @memberof GetWorkspaceRepsonseDTO
     */
    'id': number;
    /**
     * Title
     * @type {string}
     * @memberof GetWorkspaceRepsonseDTO
     */
    'title': string;
    /**
     * Order
     * @type {number}
     * @memberof GetWorkspaceRepsonseDTO
     */
    'orderNo': number;
}

