/* tslint:disable */
/* eslint-disable */
/**
 * DingDong Survey
 * dingdong-survey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OauthLoginRequest
 */
export interface OauthLoginRequest {
    /**
     * Email
     * @type {string}
     * @memberof OauthLoginRequest
     */
    'email': string;
    /**
     * User username
     * @type {string}
     * @memberof OauthLoginRequest
     */
    'username': string;
    /**
     * OAuth ID
     * @type {string}
     * @memberof OauthLoginRequest
     */
    'oauthId': string;
}

