/* tslint:disable */
/* eslint-disable */
/**
 * DingDong Survey
 * dingdong-survey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RefreshTokenRequest
 */
export interface RefreshTokenRequest {
    /**
     * Token
     * @type {string}
     * @memberof RefreshTokenRequest
     */
    'token': string;
    /**
     * Refresh token
     * @type {string}
     * @memberof RefreshTokenRequest
     */
    'refresh_token': string;
}

