/* tslint:disable */
/* eslint-disable */
/**
 * DingDong Survey
 * dingdong-survey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExperimentTimeslot } from './experiment-timeslot';
// May contain unused imports in some cases
// @ts-ignore
import type { ExperimentTypeEnum } from './experiment-type-enum';

/**
 * 
 * @export
 * @interface UpdateProjectRequestDTO
 */
export interface UpdateProjectRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectRequestDTO
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectRequestDTO
     */
    'description': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateProjectRequestDTO
     */
    'is_public': boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectRequestDTO
     */
    'start_date': string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectRequestDTO
     */
    'end_date': string | null;
    /**
     * Experimental exclusion days
     * @type {Array<string>}
     * @memberof UpdateProjectRequestDTO
     */
    'excluded_dates': Array<string>;
    /**
     * Time information of experiment
     * @type {Array<ExperimentTimeslot>}
     * @memberof UpdateProjectRequestDTO
     */
    'experiment_timeslots': Array<ExperimentTimeslot>;
    /**
     * Maximum number of experiment participants
     * @type {number}
     * @memberof UpdateProjectRequestDTO
     */
    'max_participants': number;
    /**
     * 
     * @type {ExperimentTypeEnum}
     * @memberof UpdateProjectRequestDTO
     */
    'experiment_type': ExperimentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectRequestDTO
     */
    'location': string;
}



