/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateProjectRequest,
  CreateProjectResponse,
  GetExperimentParticipantResponse,
  GetExperimentProjectResponse,
  GetProjectListResponse,
  HTTPValidationError,
  ProjectTypeEnum,
  PutProjectRequest,
} from '../models/index';
import {
    CreateProjectRequestFromJSON,
    CreateProjectRequestToJSON,
    CreateProjectResponseFromJSON,
    CreateProjectResponseToJSON,
    GetExperimentParticipantResponseFromJSON,
    GetExperimentParticipantResponseToJSON,
    GetExperimentProjectResponseFromJSON,
    GetExperimentProjectResponseToJSON,
    GetProjectListResponseFromJSON,
    GetProjectListResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ProjectTypeEnumFromJSON,
    ProjectTypeEnumToJSON,
    PutProjectRequestFromJSON,
    PutProjectRequestToJSON,
} from '../models/index';

export interface CreateProjectWorkspacesWorkspaceIdProjectsPostRequest {
    workspaceId: number;
    projectType: ProjectTypeEnum;
    createProjectRequest: CreateProjectRequest;
}

export interface DeleteProjectParticipantWorkspacesWorkspaceIdProjectsProjectIdParticipantsParticipantIdDeleteRequest {
    workspaceId: number;
    projectId: number;
    participantId: number;
    projectType: ProjectTypeEnum;
}

export interface DeleteProjectWorkspacesWorkspaceIdProjectsProjectIdDeleteRequest {
    workspaceId: number;
    projectId: number;
    projectType: ProjectTypeEnum;
}

export interface GetProjectListWorkspacesWorkspaceIdProjectsGetRequest {
    workspaceId: number;
    projectType: ProjectTypeEnum;
    page?: number;
    size?: number;
}

export interface GetProjectParticipantListWorkspacesWorkspaceIdProjectsProjectIdParticipantsGetRequest {
    workspaceId: number;
    projectId: number;
    projectType: ProjectTypeEnum;
    page?: number;
    size?: number;
}

export interface GetProjectWorkspacesWorkspaceIdProjectsProjectIdGetRequest {
    workspaceId: number;
    projectId: number;
    projectType: ProjectTypeEnum;
}

export interface UpdateProjectWorkspacesWorkspaceIdProjectsProjectIdPutRequest {
    workspaceId: number;
    projectId: number;
    projectType: ProjectTypeEnum;
    putProjectRequest: PutProjectRequest;
}

/**
 * 
 */
export class ProjectApi extends runtime.BaseAPI {

    /**
     * Create Project
     */
    async createProjectWorkspacesWorkspaceIdProjectsPostRaw(requestParameters: CreateProjectWorkspacesWorkspaceIdProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateProjectResponse>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling createProjectWorkspacesWorkspaceIdProjectsPost().'
            );
        }

        if (requestParameters['projectType'] == null) {
            throw new runtime.RequiredError(
                'projectType',
                'Required parameter "projectType" was null or undefined when calling createProjectWorkspacesWorkspaceIdProjectsPost().'
            );
        }

        if (requestParameters['createProjectRequest'] == null) {
            throw new runtime.RequiredError(
                'createProjectRequest',
                'Required parameter "createProjectRequest" was null or undefined when calling createProjectWorkspacesWorkspaceIdProjectsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectType'] != null) {
            queryParameters['project_type'] = requestParameters['projectType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces/{workspace_id}/projects`.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProjectRequestToJSON(requestParameters['createProjectRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateProjectResponseFromJSON(jsonValue));
    }

    /**
     * Create Project
     */
    async createProjectWorkspacesWorkspaceIdProjectsPost(requestParameters: CreateProjectWorkspacesWorkspaceIdProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateProjectResponse> {
        const response = await this.createProjectWorkspacesWorkspaceIdProjectsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Project Participant
     */
    async deleteProjectParticipantWorkspacesWorkspaceIdProjectsProjectIdParticipantsParticipantIdDeleteRaw(requestParameters: DeleteProjectParticipantWorkspacesWorkspaceIdProjectsProjectIdParticipantsParticipantIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling deleteProjectParticipantWorkspacesWorkspaceIdProjectsProjectIdParticipantsParticipantIdDelete().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteProjectParticipantWorkspacesWorkspaceIdProjectsProjectIdParticipantsParticipantIdDelete().'
            );
        }

        if (requestParameters['participantId'] == null) {
            throw new runtime.RequiredError(
                'participantId',
                'Required parameter "participantId" was null or undefined when calling deleteProjectParticipantWorkspacesWorkspaceIdProjectsProjectIdParticipantsParticipantIdDelete().'
            );
        }

        if (requestParameters['projectType'] == null) {
            throw new runtime.RequiredError(
                'projectType',
                'Required parameter "projectType" was null or undefined when calling deleteProjectParticipantWorkspacesWorkspaceIdProjectsProjectIdParticipantsParticipantIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectType'] != null) {
            queryParameters['project_type'] = requestParameters['projectType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces/{workspace_id}/projects/{project_id}/participants/{participant_id}`.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId']))).replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"participant_id"}}`, encodeURIComponent(String(requestParameters['participantId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Project Participant
     */
    async deleteProjectParticipantWorkspacesWorkspaceIdProjectsProjectIdParticipantsParticipantIdDelete(requestParameters: DeleteProjectParticipantWorkspacesWorkspaceIdProjectsProjectIdParticipantsParticipantIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteProjectParticipantWorkspacesWorkspaceIdProjectsProjectIdParticipantsParticipantIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Project
     */
    async deleteProjectWorkspacesWorkspaceIdProjectsProjectIdDeleteRaw(requestParameters: DeleteProjectWorkspacesWorkspaceIdProjectsProjectIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling deleteProjectWorkspacesWorkspaceIdProjectsProjectIdDelete().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteProjectWorkspacesWorkspaceIdProjectsProjectIdDelete().'
            );
        }

        if (requestParameters['projectType'] == null) {
            throw new runtime.RequiredError(
                'projectType',
                'Required parameter "projectType" was null or undefined when calling deleteProjectWorkspacesWorkspaceIdProjectsProjectIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectType'] != null) {
            queryParameters['project_type'] = requestParameters['projectType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces/{workspace_id}/projects/{project_id}`.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId']))).replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Project
     */
    async deleteProjectWorkspacesWorkspaceIdProjectsProjectIdDelete(requestParameters: DeleteProjectWorkspacesWorkspaceIdProjectsProjectIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteProjectWorkspacesWorkspaceIdProjectsProjectIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Project List
     */
    async getProjectListWorkspacesWorkspaceIdProjectsGetRaw(requestParameters: GetProjectListWorkspacesWorkspaceIdProjectsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetProjectListResponse>>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getProjectListWorkspacesWorkspaceIdProjectsGet().'
            );
        }

        if (requestParameters['projectType'] == null) {
            throw new runtime.RequiredError(
                'projectType',
                'Required parameter "projectType" was null or undefined when calling getProjectListWorkspacesWorkspaceIdProjectsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectType'] != null) {
            queryParameters['project_type'] = requestParameters['projectType'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces/{workspace_id}/projects`.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetProjectListResponseFromJSON));
    }

    /**
     * Get Project List
     */
    async getProjectListWorkspacesWorkspaceIdProjectsGet(requestParameters: GetProjectListWorkspacesWorkspaceIdProjectsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetProjectListResponse>> {
        const response = await this.getProjectListWorkspacesWorkspaceIdProjectsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Project Participant List
     */
    async getProjectParticipantListWorkspacesWorkspaceIdProjectsProjectIdParticipantsGetRaw(requestParameters: GetProjectParticipantListWorkspacesWorkspaceIdProjectsProjectIdParticipantsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetExperimentParticipantResponse>>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getProjectParticipantListWorkspacesWorkspaceIdProjectsProjectIdParticipantsGet().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectParticipantListWorkspacesWorkspaceIdProjectsProjectIdParticipantsGet().'
            );
        }

        if (requestParameters['projectType'] == null) {
            throw new runtime.RequiredError(
                'projectType',
                'Required parameter "projectType" was null or undefined when calling getProjectParticipantListWorkspacesWorkspaceIdProjectsProjectIdParticipantsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectType'] != null) {
            queryParameters['project_type'] = requestParameters['projectType'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces/{workspace_id}/projects/{project_id}/participants`.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId']))).replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetExperimentParticipantResponseFromJSON));
    }

    /**
     * Get Project Participant List
     */
    async getProjectParticipantListWorkspacesWorkspaceIdProjectsProjectIdParticipantsGet(requestParameters: GetProjectParticipantListWorkspacesWorkspaceIdProjectsProjectIdParticipantsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetExperimentParticipantResponse>> {
        const response = await this.getProjectParticipantListWorkspacesWorkspaceIdProjectsProjectIdParticipantsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Project
     */
    async getProjectWorkspacesWorkspaceIdProjectsProjectIdGetRaw(requestParameters: GetProjectWorkspacesWorkspaceIdProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetExperimentProjectResponse>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getProjectWorkspacesWorkspaceIdProjectsProjectIdGet().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectWorkspacesWorkspaceIdProjectsProjectIdGet().'
            );
        }

        if (requestParameters['projectType'] == null) {
            throw new runtime.RequiredError(
                'projectType',
                'Required parameter "projectType" was null or undefined when calling getProjectWorkspacesWorkspaceIdProjectsProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectType'] != null) {
            queryParameters['project_type'] = requestParameters['projectType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces/{workspace_id}/projects/{project_id}`.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId']))).replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetExperimentProjectResponseFromJSON(jsonValue));
    }

    /**
     * Get Project
     */
    async getProjectWorkspacesWorkspaceIdProjectsProjectIdGet(requestParameters: GetProjectWorkspacesWorkspaceIdProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetExperimentProjectResponse> {
        const response = await this.getProjectWorkspacesWorkspaceIdProjectsProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Project
     */
    async updateProjectWorkspacesWorkspaceIdProjectsProjectIdPutRaw(requestParameters: UpdateProjectWorkspacesWorkspaceIdProjectsProjectIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling updateProjectWorkspacesWorkspaceIdProjectsProjectIdPut().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProjectWorkspacesWorkspaceIdProjectsProjectIdPut().'
            );
        }

        if (requestParameters['projectType'] == null) {
            throw new runtime.RequiredError(
                'projectType',
                'Required parameter "projectType" was null or undefined when calling updateProjectWorkspacesWorkspaceIdProjectsProjectIdPut().'
            );
        }

        if (requestParameters['putProjectRequest'] == null) {
            throw new runtime.RequiredError(
                'putProjectRequest',
                'Required parameter "putProjectRequest" was null or undefined when calling updateProjectWorkspacesWorkspaceIdProjectsProjectIdPut().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectType'] != null) {
            queryParameters['project_type'] = requestParameters['projectType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces/{workspace_id}/projects/{project_id}`.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId']))).replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PutProjectRequestToJSON(requestParameters['putProjectRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Project
     */
    async updateProjectWorkspacesWorkspaceIdProjectsProjectIdPut(requestParameters: UpdateProjectWorkspacesWorkspaceIdProjectsProjectIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateProjectWorkspacesWorkspaceIdProjectsProjectIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
