/* tslint:disable */
/* eslint-disable */
/**
 * Survey DingDong
 * survey-dingdong API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateProjectRequest,
  CreateProjectResponse,
  CreateWorkspaceRequest,
  CreateWorkspaceResponse,
  GetProjectListResponse,
  GetWorkspaceListResponse,
  HTTPValidationError,
  ProjectTypeEnum,
  UpdateWorkspaceRequest,
} from '../models/index';
import {
    CreateProjectRequestFromJSON,
    CreateProjectRequestToJSON,
    CreateProjectResponseFromJSON,
    CreateProjectResponseToJSON,
    CreateWorkspaceRequestFromJSON,
    CreateWorkspaceRequestToJSON,
    CreateWorkspaceResponseFromJSON,
    CreateWorkspaceResponseToJSON,
    GetProjectListResponseFromJSON,
    GetProjectListResponseToJSON,
    GetWorkspaceListResponseFromJSON,
    GetWorkspaceListResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ProjectTypeEnumFromJSON,
    ProjectTypeEnumToJSON,
    UpdateWorkspaceRequestFromJSON,
    UpdateWorkspaceRequestToJSON,
} from '../models/index';

export interface CreateProjectWorkspacesWorkspaceIdProjectsPostRequest {
    workspaceId: number;
    projectType: ProjectTypeEnum;
    createProjectRequest: CreateProjectRequest;
}

export interface CreateWorkspaceWorkspacesPostRequest {
    createWorkspaceRequest: CreateWorkspaceRequest;
}

export interface DeleteWorkspaceWorkspacesWorkspaceIdDeleteRequest {
    workspaceId: number;
}

export interface GetProjectListWorkspacesWorkspaceIdProjectsGetRequest {
    workspaceId: number;
    projectType: ProjectTypeEnum;
    page?: number;
    size?: number;
}

export interface UpdateWorkspaceWorkspacesWorkspaceIdPatchRequest {
    workspaceId: number;
    updateWorkspaceRequest: UpdateWorkspaceRequest;
}

/**
 * 
 */
export class WorkspaceApi extends runtime.BaseAPI {

    /**
     * Create Project
     */
    async createProjectWorkspacesWorkspaceIdProjectsPostRaw(requestParameters: CreateProjectWorkspacesWorkspaceIdProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateProjectResponse>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling createProjectWorkspacesWorkspaceIdProjectsPost().'
            );
        }

        if (requestParameters['projectType'] == null) {
            throw new runtime.RequiredError(
                'projectType',
                'Required parameter "projectType" was null or undefined when calling createProjectWorkspacesWorkspaceIdProjectsPost().'
            );
        }

        if (requestParameters['createProjectRequest'] == null) {
            throw new runtime.RequiredError(
                'createProjectRequest',
                'Required parameter "createProjectRequest" was null or undefined when calling createProjectWorkspacesWorkspaceIdProjectsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectType'] != null) {
            queryParameters['project_type'] = requestParameters['projectType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces/{workspace_id}/projects`.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProjectRequestToJSON(requestParameters['createProjectRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateProjectResponseFromJSON(jsonValue));
    }

    /**
     * Create Project
     */
    async createProjectWorkspacesWorkspaceIdProjectsPost(requestParameters: CreateProjectWorkspacesWorkspaceIdProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateProjectResponse> {
        const response = await this.createProjectWorkspacesWorkspaceIdProjectsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Workspace
     */
    async createWorkspaceWorkspacesPostRaw(requestParameters: CreateWorkspaceWorkspacesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateWorkspaceResponse>> {
        if (requestParameters['createWorkspaceRequest'] == null) {
            throw new runtime.RequiredError(
                'createWorkspaceRequest',
                'Required parameter "createWorkspaceRequest" was null or undefined when calling createWorkspaceWorkspacesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkspaceRequestToJSON(requestParameters['createWorkspaceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateWorkspaceResponseFromJSON(jsonValue));
    }

    /**
     * Create Workspace
     */
    async createWorkspaceWorkspacesPost(requestParameters: CreateWorkspaceWorkspacesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateWorkspaceResponse> {
        const response = await this.createWorkspaceWorkspacesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Workspace
     */
    async deleteWorkspaceWorkspacesWorkspaceIdDeleteRaw(requestParameters: DeleteWorkspaceWorkspacesWorkspaceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling deleteWorkspaceWorkspacesWorkspaceIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces/{workspace_id}`.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Workspace
     */
    async deleteWorkspaceWorkspacesWorkspaceIdDelete(requestParameters: DeleteWorkspaceWorkspacesWorkspaceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteWorkspaceWorkspacesWorkspaceIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Project List
     */
    async getProjectListWorkspacesWorkspaceIdProjectsGetRaw(requestParameters: GetProjectListWorkspacesWorkspaceIdProjectsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetProjectListResponse>>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getProjectListWorkspacesWorkspaceIdProjectsGet().'
            );
        }

        if (requestParameters['projectType'] == null) {
            throw new runtime.RequiredError(
                'projectType',
                'Required parameter "projectType" was null or undefined when calling getProjectListWorkspacesWorkspaceIdProjectsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectType'] != null) {
            queryParameters['project_type'] = requestParameters['projectType'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces/{workspace_id}/projects`.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetProjectListResponseFromJSON));
    }

    /**
     * Get Project List
     */
    async getProjectListWorkspacesWorkspaceIdProjectsGet(requestParameters: GetProjectListWorkspacesWorkspaceIdProjectsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetProjectListResponse>> {
        const response = await this.getProjectListWorkspacesWorkspaceIdProjectsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Workspace List
     */
    async getWorkspaceListWorkspacesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetWorkspaceListResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetWorkspaceListResponseFromJSON));
    }

    /**
     * Get Workspace List
     */
    async getWorkspaceListWorkspacesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetWorkspaceListResponse>> {
        const response = await this.getWorkspaceListWorkspacesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Workspace
     */
    async updateWorkspaceWorkspacesWorkspaceIdPatchRaw(requestParameters: UpdateWorkspaceWorkspacesWorkspaceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling updateWorkspaceWorkspacesWorkspaceIdPatch().'
            );
        }

        if (requestParameters['updateWorkspaceRequest'] == null) {
            throw new runtime.RequiredError(
                'updateWorkspaceRequest',
                'Required parameter "updateWorkspaceRequest" was null or undefined when calling updateWorkspaceWorkspacesWorkspaceIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PermissionDependency authentication
        }

        const response = await this.request({
            path: `/workspaces/{workspace_id}`.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWorkspaceRequestToJSON(requestParameters['updateWorkspaceRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Workspace
     */
    async updateWorkspaceWorkspacesWorkspaceIdPatch(requestParameters: UpdateWorkspaceWorkspacesWorkspaceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateWorkspaceWorkspacesWorkspaceIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
